from __future__ import annotations

import argparse
from pathlib import Path

from common import REPO_ROOT, load_yaml, write_text


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Assemble layered AX6600 config fragments.")
    parser.add_argument("--manifest", default="targets/ax6600/manifest.yml")
    parser.add_argument("--output", default="build/ax6600/.config")
    parser.add_argument(
        "--optional-profiles",
        default="",
        help="Comma-separated optional profile keys from manifest.yml",
    )
    parser.add_argument(
        "--replace-default-optional-profiles",
        action="store_true",
        help="Do not include manifest release.default_optional_profiles",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    manifest = load_yaml(REPO_ROOT / args.manifest)
    selected = [item.strip() for item in args.optional_profiles.split(",") if item.strip()]
    fragments = list(manifest["config_fragments"]["base"])
    available_optional = manifest["config_fragments"].get("optional_profiles", {})
    default_optional = manifest.get("release", {}).get("default_optional_profiles", [])

    chosen_optional = [] if args.replace_default_optional_profiles else list(default_optional)
    for item in selected:
        if item not in chosen_optional:
            chosen_optional.append(item)

    missing_profiles = [item for item in chosen_optional if item not in available_optional]
    if missing_profiles:
        raise SystemExit(f"Unknown optional profile(s): {', '.join(missing_profiles)}")

    fragments.extend(available_optional[item] for item in chosen_optional)

    parts: list[str] = [
        "# Auto-generated by scripts/assemble_config.py",
        f"# target: {manifest['target']}",
        f"# optional_profiles: {', '.join(chosen_optional) if chosen_optional else 'none'}",
        "",
    ]

    for relative_path in fragments:
        source = REPO_ROOT / relative_path
        parts.append(f"# --- begin {relative_path} ---")
        parts.append(source.read_text(encoding="utf-8").rstrip())
        parts.append(f"# --- end {relative_path} ---")
        parts.append("")

    output = REPO_ROOT / args.output
    write_text(output, "\n".join(parts).rstrip() + "\n")
    print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
